import Head from "next/head";
import { Form } from "../../../components/Form";
import { useMoralis } from "react-moralis";
import * as React from "react";
import { Navbar } from "../../../components/Navbar";
import { supabase } from "../../../lib/supabase";

export async function getServerSideProps({ req }) {
  var jwt = require("jsonwebtoken");

  const key = process.env.NEXT_PUBLIC_JWT_SIGNER;
  const { user } = await supabase.auth.api.getUserByCookie(req);
  const url = req.url.replace("/portal/auth/", "");

  const token = await jwt.verify(url, key, async (err, decoded) => {
    return decoded;
  });

  return { props: { token: token, user: user } };
}

export default function Home(props) {
  const { user, isAuthenticated, authenticate, logout, Moralis } = useMoralis();

  //spoof address
  //const owner_address = "0xe41a6d406fc97ac53b9e34489fe791a821064ea0";

  const owner_address = user ? user.attributes.ethAddress : "";

  if (user) {
    return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {props.user && <Navbar props={props} href={""} />}
        <main className="min-h-screen py-24">
          <h1 className="text-5xl font-black text-center">
            📺portal for: {props.token.contract_address}
          </h1>
          <br></br>
          {user && <Form address={owner_address} props={props} />}
        </main>
      </div>
    );
  } else {
    return (
      <>
        {props.user && <Navbar props={props} href={""} />}
        <main className="min-h-screen  flex justify-center items-center">
          <div className="grid grid-cols-1 gap-6">
            <p className="text-4xl font-bold">
              📺portal for: {props.token.contract_address}
            </p>
            <button
              className="bg-indigo-500 text-white p-4 rounded-xl text-2xl font-bold"
              onClick={() =>
                authenticate({
                  signingMessage: `🎨NFTPortal: ${props.token.contract_address}`,
                })
              }
            >
              auth
            </button>
          </div>
        </main>
      </>
    );
  }
}
